### ISSUE TITLE
Incorrect rendering using LuaLaTeX 

### ISSUE THREAD

**Issue by sayol** [wspr/fontspec#206]
Khmer font renders correctly when I compile the MWE with XeLaTeX, but is not with LuaLaTeX! Some vowels are missing.

\documentclass{article}
\usepackage{fontspec}
\usepackage{xltxtra}
\newfontfamily\khmerfont[Script=Khmer]{Khmer OS}
\newcommand{\textkh}[1]{\begingroup\khmerfont#1\endgroup}
\begin{document}
    Compile this with \XeLaTeX{} to see the correct rendering.
    \par
    \textkh{តើមានអ្វីប្លែក?}
    \par
    When compile with Lua\LaTeX{} \textkh{ើ} becames \textkh{ី}
\end{document}

**Comment by reutenauer** [comment]
That’s unfortunately a limitation of LuaLaTeX: it doesn’t know how to correctly shape the glyphs when typesetting South-East Asian scripts.  That’s also the case for most Indic scripts, and I don’t think you can expect an improvement in the near future.  You probably have to stick to XeTeX for the time being.

That issue is in addition to the problem we discussed earlier about Polyglossia (LuaTeX doesn’t have an equivalent of `\XeTeXlinebreaklocale`).

**Comment by sayol** [comment]
Thank @reutenauer  for breaking my doubt! However, where can I find an official manual of LuaTeX!

**Comment by wspr** [comment]
Thanks for the semi-official response, Arthur :) I'll close this issue here as being out of my control.
