### ISSUE TITLE
Provide default fallback font for Greek

### ISSUE THREAD

**Issue by adunning** [wspr/fontspec#225]
Perhaps this is intentional; but pdfLaTeX provides a fallback font for Greek text (since it is missing in Latin Modern), while fontspec does not. Thus, the following document should in theory render with XeTeX and LuaTeX, but doesn't:

```tex
\documentclass{article}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage[shorthands=off,main=greek]{babel}
  \languageattribute{greek}{ancient}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \usepackage{polyglossia}
  \setmainlanguage[variant=ancient]{greek}
\fi

\begin{document}

Τῶν καλῶν καὶ τιμίων τὴν εἴδησιν ὑπολαμβάνοντες, μᾶλλον δ' ἑτέραν ἑτέρας
ἢ κατ' ἀκρίβειαν ἢ τῷ βελτιόνων τε καὶ θαυμασιωτέρων εἶναι, δι' ἀμφότερα
ταῦτα τὴν περὶ τῆς ψυχῆς ἱστορίαν εὐλόγως ἂν ἐν πρώτοις τιθείημεν.

\end{document}
```

The resulting error is:

```
! Package polyglossia Error: The current roman font does not contain the Greek script!
(polyglossia)                Please define \greekfont with \newfontfamily.
```

**Comment by wspr** [comment]
Thanks for writing. Unfortunately the way that Unicode fonts are constructed this isn't possible in an engine-agnostic way. (In LuaTeX we could create a virtual font but I'm not yet keen on splitting the code up even further.) In pdfTeX a completely different setup is used to access greek glyphs from unicode input, and this setup isn't mirrored in XeTeX or LuaTeX since it's not needed.

The generally philosophy for this sort of thing, at least up until now, has been that you need to carefully chose the fonts you use for the document — if LM doesn't have Greek, then it is sensible to load a new font `:)` I think the `polyglossia` error does a (really) good job of indicating this.

So I'm afraid I'm going to have to close this here, apologies!

**Comment by adunning** [comment]
I mainly wanted to check that you weren't intending to mirror the behaviour of pdfLaTeX; it's certainly only a minor inconvenience. Thanks for the explanation, and for all your work on this!

**Comment by reutenauer** [comment]
This kind of capability would be the responsibility of Polyglossia, actually, not fontspec; just like, with pdfTeX, Babel is the package that sets a default font for Greek.  However, since in XeTeX and LuaTeX one has access to many more fonts for, say, Greek than in pdfTeX, it is not always desirable to have a package change the font whenever the language changes, and Polyglossia thus lets the user set the font they need (indeed, this was one of the reasons Polyglossia was written in the first place).

There is sometimes talk on mailing lists about having language-based default fonts, but it’s not completely clear what the user interface should be and I wouldn’t make that a priority.
