### ISSUE TITLE
microtype warnings and missing italic

### ISSUE THREAD

**Issue by rpfei74** [wspr/fontspec#258]
Since the recent font spec update to v2.5c in TeXlive, I do get a lot of warnings like

Package microtype Warning: Unknown slot number of character
(microtype)                `\`i'
(microtype)                in font encoding `TU' in inheritance list
(microtype)                `microtype.cfg/358(protrusion)'.

Additionally, all emphasized and italic text comes out as normal text when using lualatex 0.95.0.

**Comment by rpfei74** [comment]
OK, after restoring to v2.5a I get the same problems. Must be another package.

**Comment by davidcarlisle** [comment]
the unknown slot warning as the tuenc.def distributed (now) with latex does not declare\'i just \'\i this has been fixed in 2017/01/01 patch level 1 which was uploaded to ctan last night so should get distributed in the next day or so see issue #256

If you use the new feature of using TU encoding without loading fontspec, microtype loads its default cmr config not the one tuned for opentype latin modern, we've written to the microtype author to catch that or you can add

`\DeclareMicrotypeAlias{lmr} {Latin Modern Roman}`

after loading microtype.

italic text (`\textit`) should work? but `\emph` was broken in fontspec for the previous release, I fixed version went to CTAN yesterday see issue #254

**Comment by rpfei74** [comment]
Yes, \textit is working

**Comment by wspr** [comment]
Thanks all — I'll close this now but let me know if the problems persist.
