### ISSUE TITLE
Font name vs file name selection

### ISSUE THREAD

**Issue by Stone-Zeng** [wspr/fontspec#314]
Is there any efficiency difference between these two methods? I guess that by font name, `fontspec` will do more things to parse the font name, so it will be slower then.

**Comment by wspr** [comment]
I would guess that there is a difference. And the difference would vary between XeTeX and LuaTeX as well. 

It would be hard to test reliably since caching makes such a big difference to the performance.

Generally speaking, finding fonts is fast unless the font doesn’t exist — I wouldn’t worry too much about which is faster unless you’re loading fonts 100s of times in a document, which I assume you wouldn’t be!

Do you need me to keep this issue “open”?

**Comment by Stone-Zeng** [comment]
You can close it. Could you give some advice of the best practice? Or do you have some personal preference?

**Comment by wspr** [comment]
I definitely recommend loading fonts by file name. Especially with XeTeX it makes documents more portable and means you don't have "know" the proper name of the font to load it with. The only downside is specifying italic/bold separately (in XeTeX).

**Comment by Stone-Zeng** [comment]
In the section 1.2 (Font selection by file name) of `fontspec` document:

> This technique is also necessary in XeTeX when loading OpenType fonts that are present within your TeX distribution, such as `/usr/local/texlive/2013/texmf-dist/fonts/opentype/public`. Fonts in such locations are visible to XeTeX but cannot be loaded by font name, only file name; LuaTeX does not have this restriction.

I have notice that in my Windows and Ubuntu system, fonts in TEXMF tree are actually accessible via font names (in XeTeX). But in macOS, it seems not impossible to do such things. IMHO it is related to `fontconfig`. So should there be more explanation in the document?

**Comment by wspr** [comment]
Thanks -- I've made a very minor update to the documentation to address this.
