### ISSUE TITLE
LetterSpace is ignored when using LuaTex

### ISSUE THREAD

**Issue by lunik1** [wspr/fontspec#362]
## Description
LetterSpace is ignored when using LuaTeX.

The code snippet below has no effect on letter spacing in LuaTeX. With XeTeX the letter spacing is increased, as expected.

## Check/indicate
- [ ] Relevant for XeTeX
- [x] Relevant for LuaTeX
- [x] Issue tracker has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate

## Minimal example demonstrating the issue
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{DejaVuSerif.ttf}[LetterSpace=50]
\begin{document}
Pack my box with five dozen liquor jugs.
\end{document}
```

## Further details
I have observed this on two Arch Linux systems with TexLive 2018, LuaTeX 1.07.0, and fontspec 2.7b. It was not reproducible on a mac with TexLive 2018, LuaTex 1.07.0, and fontspec 2.6g.

**Comment by choreutes** [comment]
I also encoutered this issue on an Arch Linux system, running LuaTeX 1.07 and fontspec 2.7b. I might try downgrading to a previous version of fontspec to see if this is a regression or not, but otherwise I am pretty much lost, as I don't have nearly enough experience with this level of TeX coding.

Is there anything I might be able to do to help you fix this, @wspr ?

**Comment by eg9** [comment]
@choreutes  Upgrade your TeX system. If Arch Linux doesn't provide TeX Live 2019, install it manually following instructions at https://tug.org/texlive

**Comment by lunik1** [comment]
This is fixed with TexLive 2019, now in the Arch repositories.
