### ISSUE TITLE
French kerning

### ISSUE THREAD

**Issue by Guerin-sudo** [wspr/fontspec#408]
## Description

I'd like to request an option in XeLaTeX and LuaLaTeX to mimic the French kerning option. This is available in regular LaTeX through the microtype package, but not XeLaTeX. Essentially it adds a full space between the previous letter and a colon, and a half space between the previous letter and a semicolon, exclamation mark and question mark. I suspect this could be done by modifying the XeLaTeX config file but I am too much a newbie to know how to do that on a glyph-by-glyph basis. And it would be good to have it available for everyone.

Motivation: When French kerning has come up on stack exchange there are howls of protest that it is just wrong. I disagree. I have looked at many well-typeset books from the past and "French" kerning is the standard for publications in English, and was so well into the 20th Century. In my own case I want to produce in XeLaTeX a typographically similar version of a philosophical text from David Hume, so that a modern reader gets the feel of what it was like to read the book as the author approved it in 1768. 

This is my first post so apologies in advance if it breaks protocol in any way. Thank you for fontspec -- it is a great piece of work.

**Comment by reutenauer** [comment]
No-break spaces and thin spaces before ”tall” punctuation are usually handled in a font-independent way as language options.  I’ve never heard of the idea of using microtype for that.  Using kerning seems inefficient as you would have to consider many character pairs instead of single punctuation marks.

I suggest you request an option for English in Babel or Polyglossia.  It’s a reasonable request.

**Comment by wspr** [comment]
Thanks for writing. In an ideal world I believe this would be a font option, but I've never heard of a font designer implementing this. Unfortunately while fontspec is cross-platform (both XeTeX and LuaTeX) there is no built-in way this could be done. It would almost certainly be possible in LuaLaTeX by adjusting glyph metrics but I don't have code to demonstrate... In XeTeX the best approach (I think) would be using inter char classes. (See package interchar.) Again, not something that fontspec can manage internally. So I will have to close the issue here, but good like finding a good solution!

**Comment by tail-reversion** [comment]
I know that the font Junicode provides French kerning via a style set. However, I don’t know of any other font that does this.
